### ISSUE TITLE
New API Key for DIP API

### ISSUE THREAD

**Issue by hejjoe** [lichtbaer/pydipapi#1]
Old key is used here: https://github.com/lichtbaer/pydipapi/blob/master/pydipapi/api.py#L5

> Zur Nutzung ist ein API-Key notwendig. Der zunächst bis Ende Mai 2023 gültige API-Key lautet:
> GmEPb1B.bfqJLIhcGAsH9fTJevTglhFpCoZyAAAdhp
> 
> Auf Anfrage können Sie auch einen eigenen API Key erhalten, der zeitlich unbefristet ist.
> 
> Bitte stellen Sie eine diesbezügliche Anfrage per E-Mail an: parlamentsdokumentation@bundestag.de

https://dip.bundestag.de/%C3%BCber-dip/hilfe/api#content

**Comment by hejjoe** [comment]
Old key is still used here: https://github.com/lichtbaer/pydipapi/blob/master/pydipapi/api.py#L5

> Zur Nutzung ist ein API-Key notwendig. Der zunächst bis Ende Mai 2025 gültige API-Key lautet:
> I9FKdCn.hbfefNWCY336dL6x62vfwNKpoN2RZ1gp21
> 
> Auf Anfrage können Sie auch einen eigenen API-Key mit einer Laufzeit von zunächst zehn Jahren erhalten. Ein eigener API-Key hat denselben Funktionsumfang wie der öffentliche API-Key.
> 
> Bitte stellen Sie eine diesbezügliche Anfrage per E-Mail an: [parlamentsdokumentation@bundestag.de](mailto:parlamentsdokumentation@bundestag.de)

https://dip.bundestag.de/%C3%BCber-dip/hilfe/api#content

**Comment by lichtbaer** [comment]
fixed - the package was no longer maintained for a long time. is now fixed. we no longer use a key, the user has to maintain it himself.
